### ISSUE TITLE
Feature request type="barplot"

### ISSUE THREAD

**Issue by skanskan** [daattali/ggExtra#102]
Please add the option for ggMarginal, type="barplot".
With "histogram" we can't use discrete variables.

**Comment by crew102** [comment]
Hi @skanskan, by "discrete variables" are you talking about factor/character variables? `ggMarginal()` requires that the user pass in a scatter plot for the main plot, and since a scatter plot requires a numeric x and y aesthetic (i.e., not a factor/character variable for x and y aesthetic), it would not be possible to create a marginal distribution of a factor variable.

**Comment by skanskan** [comment]
Yes I'm talking about a factor variable.
I'm creating a geom_tile() plot with two factor variables and I'd like to add marginal barplots.

**Comment by crew102** [comment]
A similar feature request was made in #98. @skanskan , you can refer to the comments mentioned in that thread for why this feature will likely not be implemented.

**Comment by daattali** [comment]
@skanskan this feature will not be supported, from the reasons @crew102 pointed out
