### ISSUE TITLE
Marginal boxplot to histogram not working

### ISSUE THREAD

**Issue by peterolejua** [daattali/ggExtra#131]
Hello I want a marginal boxplot to a histogram. Like a year ago I could do it with the same code below

```{r }
library(ggplot2)
library(ggExtra)

set.seed(17)

x <- rpois(10000,lambda = 2)


c <- ggplot() + 
  geom_histogram(aes(x),fill='lightblue',closed='left', bins = 10)+
  geom_vline(xintercept= quantile(x),linetype = 3,colour = "Red")+
  theme_bw()

d <- ggMarginal(c, type = "boxplot", fill="lightblue",colour='blue',margins='x',size=30)

d
```

![image](https://user-images.githubusercontent.com/7348041/46897763-7293f100-ce4a-11e8-90a0-42ad7b382c2e.png)

Clearly the boxplot doesn´t correspond to what it is supposed to. I appreciate any help.

Best regards,

Peter

**Comment by crew102** [comment]
Hi Peter, `ggMarginal()` requires that the main plot is a scatter plot (and not a histogram, as you have there). I'm not sure why/how it would have worked for you in the past.

**Comment by peterolejua** [comment]
Well I did it in the past like this:

````r
qu <- quantile(estancia.uci)

c <- ggplot(data = uci, aes(estancia.uci)) + 
  geom_histogram(breaks=seq(0, 2000, by =30),fill='lightblue',closed='left')+
  xlab("# Días")+
  ylab("# Pacientes")+
  labs(colour="",
       title="Tiempo de estancia en la UCI")+
  geom_vline(data= uci, xintercept= qu,linetype = 3,colour = "Red")+
  scale_x_continuous(breaks = seq(0,2000,200))+
  scale_y_continuous(breaks = seq(0,30,2))+
  theme_bw()

d <- ggMarginal(c, type = "boxplot", fill="lightblue",colour='blue',margins='x',size=30)

tiff('estancia.tiff',width = 720)
d
dev.off()
````

and it gave me this:

![image](https://user-images.githubusercontent.com/7348041/46899105-0ff42280-ce55-11e8-87b3-a52eb50151f1.png)


So I guess that it is possible to make your function able to it again,

Thank you very much!

**Comment by daattali** [comment]
Hi Peter,
It's interesting that this used to work for you, because it was never an intended feature. The documentation and examples were always explicit in saying that this function adds marginal plots to **scatter plots**.
I'm sorry that histograms aren't supported any longer, if I had known that they worked in the past I would have added a comment saying this behaviour may not remain forever. Unfortunately because this is meant to be a supported feature, I'm going to close this issue. I hope it's not breaking anything extremely critical for you. If you must still use this "feature", you can re-install an old version. Again, sorry for the inconvenience!
