### ISSUE TITLE
Marginals from different data

### ISSUE THREAD

**Issue by dkulp2** [daattali/ggExtra#162]
I'd like to display marginals from a different, (much) larger data set. The idea is to show that the points in my scatter plot are in the tails of the x and y distributions.
I expected that providing the data parameter would override the data used in the plot. But it seems to be ignored.

**Comment by daattali** [comment]
Apologies for letting this issue go quiet for so long. Please see an old discussion [here](https://github.com/daattali/ggExtra/pull/110) for why what you want is not meant to work.

I really should update the docs to make that clear. You can provide `data`,`x`,`y` INSTEAD of `p`, not in addition to `p`
