### ISSUE TITLE
`groupFill` uses `colour` aes?

### ISSUE THREAD

**Issue by jessexknight** [daattali/ggExtra#168]
Thanks for all your work.

Because `groupFill` uses the `color` aes for the marginal `fill` ([see here](https://github.com/daattali/ggExtra/blob/f168a213e96253c666d1bb4707dbf127c665d54c/R/ggMarginal-MarginalPlot.R#L94)), fill-based shapes ([21-25](http://www.sthda.com/english/wiki/ggplot2-point-shapes)) don't get their fills mapped to the marginals.

Perhaps we can simply allow use-specified `aes` to `ggMarginal` instead of `groupFill` and `groupColour`, with the current behaviour as default if none given?

**MWE**
```R
library('ggplot2')
library('ggExtra')
N = 1000
df = data.frame(x=runif(N),y=runif(N),g=cut(runif(N),3))
g = ggplot(df,aes(x=x,y=y,fill=g)) +
  geom_point(color='white',shape=21) +
  theme(legend.position='none')
g = ggMarginal(g,groupFill=TRUE)
print(g)
```
Actual | Desired
--- | ---
![Rplots](https://user-images.githubusercontent.com/14393754/184408282-9439de90-4927-44b4-99d0-24756c0b242c.png) | ![Rplots-fix](https://user-images.githubusercontent.com/14393754/184409169-769a60aa-1b21-4455-b7da-c18d354ef028.png)

**Comment by crew102** [comment]
Hey @jessexknight , thanks for bringing this to our attention. My initial thought is that the flexibility that you're looking for re: being able to have a user-specified mapping of how the aesthetics of the scatter plot should map to the aesthetics of the marginal plots is probably not a good fit for ggMaringal. The function attempts to support *most* use cases, with the idea being that if you want to do further customization of the marginal plots in a way that isn't supported (e.g., theming the marginal plots, adding axis scales to the marginal plots, doing custom mappings as you're describing, etc.), a more flexible package and/or approach should be used instead. Here's some additional context around that thought:

* In my experience, the use of `fill` in scatterplots is pretty rare, and is limited to a situation where you're trying to almost style the points so that they're hollow or have some outer lining (similar to what you're doing). I suppose ggMarginal could look to see if `fill` is the aesthetic in the scatter plot instead of `colour` and do the marginal mappings from there, but again, it's probably too much of an edge case to be worth supporting.
* I don't think the user would be able to provide a call to `aes()` that we could use as-is to create the marginal plots, as there's quite a bit of jerry-rigging that we do behind the scenes to create the final call to `aes()` for the marginal plots, and that would need to somehow be replicated for any user-provided `aes()`.
* I agree that the behavior you observed is slightly unexpected, but we do document the behavior in the `groupFill` and `groupColour` parameter docs. Perhaps we should be more explicit re: the fact that scatterplot `fill` is never mapped to the marginals, or add some kind of warning when the user passes sets groupFill to TRUE and also has fill mapped in their scatter plot.

**Comment by jessexknight** [comment]
Thanks @crew102 for considering. I can see it's an edge case and understand not supporting it. You're right that I am mainly trying to tweak the styling (original use-case & work-around calling `geom_point` twice [here](https://github.com/mishra-lab/mpox-model-netcb/blob/7ffe220/code/model/plot.r#L20)). Thinking more on this, I almost feel the true problem is upstream at ggplot2, having shapes 21-25 that behave differently than the rest w.r.t. color vs fill. But probably they were introduced for some pesky edge case too...
