### ISSUE TITLE
The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.

### ISSUE THREAD

**Issue by Ahmad10Raza** [daattali/ggExtra#175]
Warning message:
The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.
ℹ The deprecated feature was likely used in the ggExtra package.
  Please report the issue at <https://github.com/daattali/ggExtra/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by daattali** [comment]
Thanks for the report! After looking into it, it looks like `after_stat()` was only introduced in ggplot2 3.3.0 - the previous minor version. It seems a little aggressive to force update when only a single minor version has changed. I'm inclined to keep `..density..` for now in order to support previous ggplot2 versions

**Comment by petzi53** [comment]
As far as I know, the dot-dot notation `(..density..)` was really deprecated in {ggplot2} beginning with version 3.4.0 for all later versions and replaced with `after_stat(density)`.

**Comment by daattali** [comment]
Thanks for the reminder, fixed
