### ISSUE TITLE
split violing plots  [feature request]

### ISSUE THREAD

**Issue by RMHogervorst** [daattali/ggExtra#33]
I love the package, can I suggest a new geom? 
Or is there another ggplot extension where this would fit better?

a split violin plot. That is, two densities of groups with the backs to eachother. This stack overflow question has a custum function, but it might be something to add? 

https://stackoverflow.com/questions/35717353/split-violin-plot-with-ggplot2

**Comment by daattali** [comment]
If the code for it is already ready and it just needs to be packaged nicely, I wouldn't mind having it in ggExtra because it will only make my package better :)

But frankly I think ggExtra is mostly synonymous with just ggmarginal, and there are some other packages that do a great job at adding geoms to ggplot2. I don't know which one is the best but if you look through the packages at [http://www.ggplot2-exts.org/gallery/](http://www.ggplot2-exts.org/gallery/) you'll find some that specialize in adding different geoms

**Comment by RMHogervorst** [comment]
Thanks a lot, I agree that it would fit better in other gg extensions. I dropped the suggestion in https://github.com/hrbrmstr/ggalt/issues/24.
