### ISSUE TITLE
Should ggMarginal suppress warnings when type = boxplot or density

### ISSUE THREAD

**Issue by crew102** [daattali/ggExtra#52]
Depending on the type of marginal plot, `ggMarginal` will pass along one of these warnings:

1. `type = histogram` - i.e., `ggMarginal(data = mtcars, x = "mpg", y = "wt", type = "histogram")`
````
`stat_bin()` using `bins = 30`.
Pick better value with
`binwidth`.
````
2. `type = boxplot` - i.e., `ggMarginal(data = mtcars, x = "mpg", y = "wt", type = "boxplot")`
````
Warning messages:
1: Continuous x aesthetic -- did you forget aes(group=...)? 
2: Continuous x aesthetic -- did you forget aes(group=...)? 
3: Continuous x aesthetic -- did you forget aes(group=...)? 
````
3. `type = density` - i.e., `ggMarginal(data = mtcars, x = "mpg", y = "wt", type = "density")`
````
Warning: Ignoring unknown parameters: fill
Warning: Ignoring unknown parameters: fill
````

In my opinion we should only pass along the warning in case number 1 (i.e., the binwidth warning when `type = histogram`). The other two warnings are not helpful and are the result of expected behavior. What do you think - should we suppress these warnings?

**Comment by daattali** [comment]
I agree that the boxplot message should not appear, good point, it should
be suppressed. The density warning should not be happening at all though,
is it possible that the refactor introduced it? I had these few lines added
a while back that explicitly remove the 'fill' parameter when using a
density plot to avoid this message
https://github.com/daattali/ggExtra/blob/master/R/ggMarginal.R#L96-L99

If possible, it'd be good to re-introduce that logic so that the warning
doesn't happen

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by crew102** [comment]
Ah yes, I removed `extraParams[['fill']] <- NULL` b/c I thought it was intended to prevent failure of the function when there was a non-null fill (which maybe it was), and since I wasn't seeing it fail in those cases, I removed it. So the warning message for density is new to the refactor. I will add that logic back.

**Comment by daattali** [comment]
Point 3 should be fixed with #40 

Point 1 we agreed should remain

Point 2 I don't think was addressed in #40 ?

**Comment by crew102** [comment]
I was going to address in separate PR

**Comment by daattali** [comment]
Sounds good!
