### ISSUE TITLE
ggMarginal applies to only first layer

### ISSUE THREAD

**Issue by kuriwaki** [daattali/ggExtra#67]
It seems like `ggMarginal` is sensitive to the order of layers; it tries to take the layer that was first added. Any way to guide it to a specific geom? 

``` r
library(ggplot2)
library(ggExtra)

p1 <- ggplot2::ggplot(mtcars, ggplot2::aes(wt, mpg)) +
  ggplot2::geom_hline(yintercept = 20) +
  ggplot2::geom_point()

# breaks 
ggMarginal(p1)
#> Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE, : arguments imply differing number of rows: 0, 1

p2 <- ggplot2::ggplot(mtcars, ggplot2::aes(wt, mpg)) +
  ggplot2::geom_point() +
  ggplot2::geom_hline(yintercept = 20)

# works
ggMarginal(p2)
```

**Comment by daattali** [comment]
That is indeed a bug. I'm surprised nobody has caught that until now. It happens because ggMarginal currently doesn't take the entire plot and add marginal plots to it, instead of tries to reconstruct the plot based on information scraped from it. Unfortunately I can't give you a workaround at the moment. Thanks for reporting!

**Comment by crew102** [comment]
I'll submit an updated PR for the marginal mapping feature once this is merged

**Comment by daattali** [comment]
Hi @kuriwaki , this should be fixed now - you can thank @crew102 for doing that :)

**Comment by kuriwaki** [comment]
thanks so much for the quick fix!
